version: "3.8"

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "4533:4533"
    volumes:
      - /docker/navidrome/data:/data
      - /docker/navidrome/music:/music
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    ports:
      - "8686:8686"
    volumes:
      - /docker/navidrome/config:/config
      - /docker/navidrome/music:/music
      - /docker/navidrome/downloads:/downloads
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    ports:
      - "8080:8080"
    volumes:
      - /docker/navidrome/config:/config
      - /docker/navidrome/downloads:/downloads
    restart: unless-stopped
  
  soularr:
    image: mrusse08/soularr:latest
    restart: unless-stopped
    container_name: soularr
    hostname: soularr
    environment: 
      - TZ=Etc/UTC
      - SCRIPT_INTERVAL=300
    volumes:
      - /docker/navidrome/downloads:/downloads
      - /docker/navidrome/data:/data
       
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    restart: unless-stopped
    container_name: jackett
    environment:
      - TZ=Europe/Madrid
      - AUTO_UPDATE=true
    volumes:
      - /docker/navidrome/config:/config
      - /docker/navidrome/downloads:/data/torrents
    ports:
      - 9117:9117