version: '3.7'

services:
  watchtower:
    container_name: watchtower
     image: containrrr/watchtower
     volumes: 
        - /var/run/docker.sock:/var/run/docker.sock 
     environment: 
        - WATCHTOWER_CLEANUP=true 
        - WATCHTOWER_INCLUDE_RESTARTING=true 
        - WATCHTOWER_INCLUDE_STOPPED=true 
        - WATCHTOWER_REVIVE_STOPPED=false 
        - WATCHTOWER_NO_RESTART=false 
        - WATCHTOWER_TIMEOUT=30s 
        - TZ=Europe/Madrid 
      network_mode: bridge
