version: "3.5"
services: 
 watchtower: 
     image: containrrr/watchtower:latest 
     container_name: watchtower 
     restart: unless-stopped 
     volumes: 
        - /var/run/docker.sock:/var/run/docker.sock environment: 
        - WATCHTOWER_CLEANUP=true 
        - WATCHTOWER_INCLUDE_RESTARTING=true 
        - WATCHTOWER_INCLUDE_STOPPED=true 
        - WATCHTOWER_REVIVE_STOPPED=false 
        - WATCHTOWER_NO_RESTART=false 
        - WATCHTOWER_TIMEOUT=30s 
        $- WATCHTOWER_SCHEDULE=0 0 4 * * * 
        $- WATCHTOWER_DEBUG=false 
        $- WATCHTOWER_NOTIFICATION_URL=telegram://BOT_TOKEN@telegram/?channels=CHAT_ID 
        - TZ=Europe/Madrid 
      network_mode: bridge