version: "3.9"
services:
  audiobookshelf:
    container_name: Audiobookshelf
    image: advplyr/audiobookshelf
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 13378:80
    volumes:
      - /volume1/docker/audiobookshelf:/config:rw
      - /volume1/docker/audiobookshelf/audiobooks:/audiobooks:rw
      - /volume1/docker/audiobookshelf/metadata:/metadata:rw
    environment:
      PUID: 1026
      PGID: 100
