version: '3.5'

services:
  pialert:
    container_name: pialert
    image: jokobsk/pi.alert:latest
    volumes:
      - /volume1/docker/pialert/config:/home/pi/pialert/config
      - /volume1/docker/pihole-unbound/pihole-configs/pihole-FTL.db:/etc/pihole/pihole-FTL.db:ro
      - /volume1/docker/pialert/db/pialert.db:/home/pi/pialert/db/pialert.db
    environment:
      - TZ=Europe/Madrid
      - PORT=20212
      - USER_ID=1000
      - USER_GID=1000
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
    restart: unless-stopped
    network_mode: host
